-- Script para agregar Foreign Keys a LTEB_PROMOCION

-- Agregar FK para SERVICIO_ID
ALTER TABLE LTEB_PROMOCION
ADD CONSTRAINT FK_PROMOCION_SERVICIO
FOREIGN KEY (SERVICIO_ID)
REFERENCES LTEB_SERVICIO(ID_SERVICIO);

-- Agregar FK para PRODUCTO_ID
ALTER TABLE LTEB_PROMOCION
ADD CONSTRAINT FK_PROMOCION_PRODUCTO
FOREIGN KEY (PRODUCTO_ID)
REFERENCES LTEB_PRODUCTO(ID_PRODUCTO);

COMMIT;
EXIT;
