-- Consultar estructura de las tablas de dirección
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'LTEB_DIRECCION'
ORDER BY COLUMN_ID;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'LTEB_CIUDAD'
ORDER BY COLUMN_ID;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'LTEB_REGION'
ORDER BY COLUMN_ID;

-- Ver datos actuales
SELECT * FROM LTEB_DIRECCION;
SELECT * FROM LTEB_CIUDAD;
SELECT * FROM LTEB_REGION;
