-- Script para crear las secuencias necesarias para el backend
-- Ejecutar este script en Oracle Database

-- Secuencias para las tablas principales
CREATE SEQUENCE LTEB_CLIENTE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_CITA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_BARBERO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_SERVICIO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_PRODUCTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_PROMOCION_SEQ START WITH 1 INCREMENT BY 1;

-- Otras secuencias que puedan ser necesarias
CREATE SEQUENCE LTEB_VENTA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_PAGO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_EVALUACION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_HORA_DISPONIBLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_SUCURSAL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_DIRECCION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_CIUDAD_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_REGION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_ESPECIALIDAD_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_TURNO_SEQ START WITH 1 INCREMENT BY 1;

COMMIT;

