-- Script de Migración Fase 1: Adaptación y Complementos
-- Ejecutar este script DESPUÉS de crear las tablas del modelo original

-- ============================================
-- 1. SECUENCIAS (Para tablas que no tenían)
-- ============================================
-- Verificar si existen antes de crear (bloques anónimos para evitar errores)
DECLARE
    v_count NUMBER;
BEGIN
    -- Secuencia Cliente
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LTEB_CLIENTE_SEQ';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_CLIENTE_SEQ START WITH 1 INCREMENT BY 1'; END IF;

    -- Secuencia Barbero
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LTEB_BARBERO_SEQ';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_BARBERO_SEQ START WITH 1 INCREMENT BY 1'; END IF;

    -- Secuencia Servicio
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LTEB_SERVICIO_SEQ';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_SERVICIO_SEQ START WITH 1 INCREMENT BY 1'; END IF;

    -- Secuencia Producto
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LTEB_PRODUCTO_SEQ';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_PRODUCTO_SEQ START WITH 1 INCREMENT BY 1'; END IF;

    -- Secuencia Cita
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LTEB_CITA_SEQ';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_CITA_SEQ START WITH 1 INCREMENT BY 1'; END IF;

    -- Secuencia Venta
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LTEB_VENTA_SEQ';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_VENTA_SEQ START WITH 1 INCREMENT BY 1'; END IF;

    -- Secuencia Pago
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LTEB_PAGO_SEQ';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_PAGO_SEQ START WITH 1 INCREMENT BY 1'; END IF;
    
    -- Secuencia Evaluacion
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'LTEB_EVALUACION_SEQ';
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_EVALUACION_SEQ START WITH 1 INCREMENT BY 1'; END IF;
END;
/

CREATE SEQUENCE LTEB_INVENTARIO_MOV_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LTEB_AUDITORIA_SEQ START WITH 1 INCREMENT BY 1;

-- ============================================
-- 2. NUEVAS TABLAS (Complementarias)
-- ============================================

    OPERACION VARCHAR2(20) NOT NULL, -- INSERT, UPDATE, DELETE
    USUARIO_BD VARCHAR2(50) DEFAULT USER,
    FECHA DATE DEFAULT SYSDATE,
    DATOS_ANTIGUOS VARCHAR2(4000),
    DATOS_NUEVOS VARCHAR2(4000)
);

-- ============================================
-- 3. ADAPTACIÓN DE TABLAS EXISTENTES
-- ============================================

-- Agregar campos faltantes a VENTA para hacerla más robusta
ALTER TABLE LTEB_VENTA ADD TOTAL NUMBER(10,2) DEFAULT 0;
ALTER TABLE LTEB_VENTA ADD ESTADO VARCHAR2(20) DEFAULT 'COMPLETADA';

-- Agregar descripción a SERVICIO (Requerimiento Usuario)
ALTER TABLE LTEB_SERVICIO ADD DESCRIPCION VARCHAR2(255);
ALTER TABLE LTEB_SERVICIO ADD ACTIVO NUMBER(1,0) DEFAULT 1;

-- ============================================
-- 4. TRIGGERS PARA AUTO-INCREMENTO (Requerimiento Usuario)
-- ============================================

-- Trigger Cliente
CREATE OR REPLACE TRIGGER TRG_BI_CLIENTE
BEFORE INSERT ON LTEB_CLIENTE FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN SELECT LTEB_CLIENTE_SEQ.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL; END IF;
END;
/

-- Trigger Barbero
CREATE OR REPLACE TRIGGER TRG_BI_BARBERO
BEFORE INSERT ON LTEB_BARBERO FOR EACH ROW
BEGIN
    IF :NEW.ID_BARBERO IS NULL THEN SELECT LTEB_BARBERO_SEQ.NEXTVAL INTO :NEW.ID_BARBERO FROM DUAL; END IF;
END;
/

-- Trigger Servicio
CREATE OR REPLACE TRIGGER TRG_BI_SERVICIO
BEFORE INSERT ON LTEB_SERVICIO FOR EACH ROW
BEGIN
    IF :NEW.ID_SERVICIO IS NULL THEN SELECT LTEB_SERVICIO_SEQ.NEXTVAL INTO :NEW.ID_SERVICIO FROM DUAL; END IF;
END;
/

-- Trigger Producto
CREATE OR REPLACE TRIGGER TRG_BI_PRODUCTO
BEFORE INSERT ON LTEB_PRODUCTO FOR EACH ROW
BEGIN
    IF :NEW.ID_PRODUCTO IS NULL THEN SELECT LTEB_PRODUCTO_SEQ.NEXTVAL INTO :NEW.ID_PRODUCTO FROM DUAL; END IF;
END;
/

-- Trigger Cita
CREATE OR REPLACE TRIGGER TRG_BI_CITA
BEFORE INSERT ON LTEB_CITA FOR EACH ROW
BEGIN
    IF :NEW.ID_CITA IS NULL THEN SELECT LTEB_CITA_SEQ.NEXTVAL INTO :NEW.ID_CITA FROM DUAL; END IF;
END;
/

-- Trigger Venta
CREATE OR REPLACE TRIGGER TRG_BI_VENTA
BEFORE INSERT ON LTEB_VENTA FOR EACH ROW
BEGIN
    IF :NEW.ID_VENTA IS NULL THEN SELECT LTEB_VENTA_SEQ.NEXTVAL INTO :NEW.ID_VENTA FROM DUAL; END IF;
END;
/

-- Trigger Pago
CREATE OR REPLACE TRIGGER TRG_BI_PAGO
BEFORE INSERT ON LTEB_PAGO FOR EACH ROW
BEGIN
    IF :NEW.ID_PAGO IS NULL THEN SELECT LTEB_PAGO_SEQ.NEXTVAL INTO :NEW.ID_PAGO FROM DUAL; END IF;
END;
/

-- Trigger Evaluacion
CREATE OR REPLACE TRIGGER TRG_BI_EVALUACION
BEFORE INSERT ON LTEB_EVALUACION FOR EACH ROW
BEGIN
    IF :NEW.ID_EVALUACION IS NULL THEN SELECT LTEB_EVALUACION_SEQ.NEXTVAL INTO :NEW.ID_EVALUACION FROM DUAL; END IF;
END;
/

-- Trigger Auditoria
CREATE OR REPLACE TRIGGER TRG_BI_AUDITORIA
BEFORE INSERT ON LTEB_AUDITORIA FOR EACH ROW
BEGIN
    IF :NEW.ID_AUDITORIA IS NULL THEN SELECT LTEB_AUDITORIA_SEQ.NEXTVAL INTO :NEW.ID_AUDITORIA FROM DUAL; END IF;
END;
/

-- Trigger Inventario Mov
CREATE OR REPLACE TRIGGER TRG_BI_INVENTARIO_MOV
BEFORE INSERT ON LTEB_INVENTARIO_MOV FOR EACH ROW
BEGIN
    IF :NEW.ID_MOVIMIENTO IS NULL THEN SELECT LTEB_INVENTARIO_MOV_SEQ.NEXTVAL INTO :NEW.ID_MOVIMIENTO FROM DUAL; END IF;
END;
/

COMMIT;
