-- Script completo para configurar la base de datos
-- Ejecutar este script completo en Oracle Database

-- ============================================
-- 1. CREAR SECUENCIAS
-- ============================================
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_CLIENTE_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN -- Secuencia ya existe
      NULL;
    ELSE
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_CITA_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_BARBERO_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_SERVICIO_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_PRODUCTO_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE LTEB_PROMOCION_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- ============================================
-- 2. AGREGAR CAMPOS DE AUTENTICACIÓN A LTEB_CLIENTE
-- ============================================
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LTEB_CLIENTE ADD PASSWORD VARCHAR2(255)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN -- Columna ya existe
      NULL;
    ELSE
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LTEB_CLIENTE ADD ES_ADMIN NUMBER(1) DEFAULT 0';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LTEB_CLIENTE ADD ES_BARBERO NUMBER(1) DEFAULT 0';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LTEB_CLIENTE ADD ACTIVO NUMBER(1) DEFAULT 1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

-- ============================================
-- 3. CREAR ÍNDICES
-- ============================================
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IDX_LTEB_CLIENTE_CORREO ON LTEB_CLIENTE(CORREO)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- ============================================
-- 4. VINCULAR BARBEROS CON CLIENTES
-- ============================================
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LTEB_BARBERO ADD ID_CLIENTE NUMBER';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE LTEB_BARBERO ADD CONSTRAINT FK_LTEB_BARBERO_CLIENTE 
    FOREIGN KEY (ID_CLIENTE) REFERENCES LTEB_CLIENTE(ID_CLIENTE)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -2260 OR SQLCODE = -2275 THEN NULL; ELSE RAISE; END IF;
END;
/

-- ============================================
-- 5. ACTUALIZAR VALORES POR DEFECTO
-- ============================================
UPDATE LTEB_CLIENTE SET ES_ADMIN = 0 WHERE ES_ADMIN IS NULL;
UPDATE LTEB_CLIENTE SET ES_BARBERO = 0 WHERE ES_BARBERO IS NULL;
UPDATE LTEB_CLIENTE SET ACTIVO = 1 WHERE ACTIVO IS NULL;

COMMIT;

-- ============================================
-- VERIFICACIÓN
-- ============================================
SELECT 'Secuencias creadas correctamente' AS MENSAJE FROM DUAL;
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE 'LTEB_%';

SELECT 'Campos agregados a LTEB_CLIENTE' AS MENSAJE FROM DUAL;
SELECT COLUMN_NAME, DATA_TYPE FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'LTEB_CLIENTE' 
AND COLUMN_NAME IN ('PASSWORD', 'ES_ADMIN', 'ES_BARBERO', 'ACTIVO');

SELECT 'Configuración completada' AS MENSAJE FROM DUAL;

