---------------------------------------------------------
-- ELIMINAR TABLAS (ORDEN CORRECTO: hijas → padres)
---------------------------------------------------------

BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_PAGO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_EVALUACION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_CITA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_BARBERO_TURNO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_BARBERO_ESPECIALIDAD CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_HORA_DISPONIBLE_BARBERO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_BARBERO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_STOCK_PRODUCTO_SUCURSAL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_SUCURSAL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_TURNO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_ESPECIALIDAD CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_DETALLE_VENTA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_VENTA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_CLIENTE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_PRODUCTO_PROMOCION_SERVICIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_PRODUCTO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_PROMOCION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_SERVICIO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_DIRECCION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_CIUDAD CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LTEB_REGION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

---------------------------------------------------------
-- CREACIÓN DE TABLAS
---------------------------------------------------------

CREATE TABLE LTEB_REGION(
    ID_REGION NUMBER,
    NOMBRE VARCHAR2(70),
    CONSTRAINT PK_LTEB_REGION PRIMARY KEY (ID_REGION)
);

CREATE TABLE LTEB_CIUDAD(
    ID_CIUDAD NUMBER,
    ID_REGION NUMBER,
    NOMBRE VARCHAR2(70),
    CONSTRAINT PK_LTEB_CIUDAD PRIMARY KEY (ID_CIUDAD),
    CONSTRAINT FK_LTEB_CIUDAD_REGION FOREIGN KEY (ID_REGION) REFERENCES LTEB_REGION(ID_REGION)
);

CREATE TABLE LTEB_DIRECCION(
    ID_DIRECCION NUMBER,
    CALLE_NUMERO VARCHAR2(70),
    ID_CIUDAD NUMBER,
    CONSTRAINT PK_LTEB_DIRECCION PRIMARY KEY (ID_DIRECCION),
    CONSTRAINT FK_LTEB_DIRECCION_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES LTEB_CIUDAD(ID_CIUDAD)
);

CREATE TABLE LTEB_SERVICIO(
    ID_SERVICIO NUMBER,
    NOMBRE VARCHAR2(70),
    PRECIO NUMBER,
    CONSTRAINT PK_LTEB_SERVICIO PRIMARY KEY (ID_SERVICIO)
);

CREATE TABLE LTEB_PROMOCION(
    ID_PROMOCION NUMBER,
    DESCUENTO NUMBER,
    NOMBRE VARCHAR2(70),
    CONDICIONES VARCHAR2(200),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    CONSTRAINT PK_LTEB_PROMOCION PRIMARY KEY (ID_PROMOCION)
);

CREATE TABLE LTEB_PRODUCTO(
    ID_PRODUCTO NUMBER,
    NOMBRE VARCHAR2(70),
    DESCRIPCION VARCHAR2(200),
    PRECIO NUMBER,
    STOCK NUMBER,
    CONSTRAINT PK_LTEB_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE LTEB_PRODUCTO_PROMOCION_SERVICIO(
    ID_PROMOCION NUMBER,
    ID_PRODUCTO NUMBER,
    ID_SERVICIO NUMBER,
    ESTADO VARCHAR2(10),
    PRECIO_OFERTA NUMBER,
    STOCK_DISP NUMBER,
    CONSTRAINT PK_LTEB_PRODUCTO_PROMOCION_SERVICIO PRIMARY KEY (ID_PROMOCION,ID_PRODUCTO,ID_SERVICIO),
    CONSTRAINT FK_LTEB_PRODUCTO_PROMOCION_SERVICIO_PROMOCION FOREIGN KEY (ID_PROMOCION) REFERENCES LTEB_PROMOCION(ID_PROMOCION),
    CONSTRAINT FK_LTEB_PRODUCTO_PROMOCION_SERVICIO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES LTEB_PRODUCTO(ID_PRODUCTO),
    CONSTRAINT FK_LTEB_PRODUCTO_PROMOCION_SERVICIO_SERVICIO FOREIGN KEY (ID_SERVICIO) REFERENCES LTEB_SERVICIO(ID_SERVICIO)
);

CREATE TABLE LTEB_CLIENTE(
    ID_CLIENTE NUMBER,
    NOMBRE VARCHAR2(50),
    APELLIDOS VARCHAR2(50),
    TELEFONO NUMBER,
    CORREO VARCHAR2(70),
    ES_ADMIN NUMBER(1,0) DEFAULT 0, 
	ES_BARBERO NUMBER(1,0) DEFAULT 0, 
	ACTIVO NUMBER(1,0) DEFAULT 1,
    PASSWORD VARCHAR2(225),
    CONSTRAINT PK_LTEB_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE LTEB_HORA_DISPONIBLE(
    ID_HORA NUMBER,
    FECHA DATE,
    HORA_INICIO VARCHAR2(70),
    HORA_FIN VARCHAR2(70),
    CONSTRAINT PK_LTEB_HORA_DISPONIBLE PRIMARY KEY (ID_HORA)
);

CREATE TABLE LTEB_VENTA(
    ID_VENTA NUMBER,
    ID_CLIENTE NUMBER,
    FECHA DATE,
    CONSTRAINT PK_LTEB_VENTA PRIMARY KEY (ID_VENTA),
    CONSTRAINT FK_LTEB_VENTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES LTEB_CLIENTE(ID_CLIENTE)
);

CREATE TABLE LTEB_DETALLE_VENTA(
    ID_PRODUCTO NUMBER,
    ID_VENTA NUMBER,
    CANTIDAD NUMBER,
    PRECIO NUMBER,
    CONSTRAINT PK_LTEB_DETALLE_VENTA PRIMARY KEY (ID_PRODUCTO,ID_VENTA),
    CONSTRAINT FK_LTEB_DETALLE_VENTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES LTEB_PRODUCTO(ID_PRODUCTO),
    CONSTRAINT FK_LTEB_DETALLE_VENTA_VENTA FOREIGN KEY (ID_VENTA) REFERENCES LTEB_VENTA(ID_VENTA)
);

CREATE TABLE LTEB_ESPECIALIDAD(
    ID_ESPECIALIDAD NUMBER,
    NOMBRE VARCHAR2(50),
    CONSTRAINT PK_LTEB_ESPECIALIDAD PRIMARY KEY (ID_ESPECIALIDAD)
);

CREATE TABLE LTEB_TURNO(
    ID_TURNO NUMBER,
    NOMBRE VARCHAR2(50),
    HORA_INICIO VARCHAR2(50),
    HORA_FIN VARCHAR2(50),
    CONSTRAINT PK_LTEB_TURNO PRIMARY KEY (ID_TURNO)
);

CREATE TABLE LTEB_SUCURSAL(
    ID_SUCURSAL NUMBER,
    ID_DIRECCION NUMBER,
    CALLE_NRO VARCHAR2(70),
    NOMBRE VARCHAR2(50),
    TELEFONO NUMBER,
    CONSTRAINT PK_LTEB_SUCURSAL PRIMARY KEY (ID_SUCURSAL),
    CONSTRAINT FK_LTEB_SUCURSAL_DIRECCION FOREIGN KEY (ID_DIRECCION) REFERENCES LTEB_DIRECCION(ID_DIRECCION)
);

CREATE TABLE LTEB_STOCK_PRODUCTO_SUCURSAL(
    ID_PRODUCTO NUMBER,
    ID_SUCURSAL NUMBER,
    CANTIDAD NUMBER,
    CONSTRAINT PK_LTEB_STOCK_PRODUCTO_SUCURSAL PRIMARY KEY (ID_PRODUCTO, ID_SUCURSAL),
    CONSTRAINT FK_LTEB_STOCK_PRODUCTO_SUCURSAL_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES LTEB_PRODUCTO(ID_PRODUCTO),
    CONSTRAINT FK_LTEB_STOCK_PRODUCTO_SUCURSAL_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES LTEB_SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE LTEB_BARBERO(
    ID_BARBERO NUMBER,
    RUT NUMBER,
    CORREO VARCHAR2(70),
    TELEFONO NUMBER,
    APELLIDO_PATERNO VARCHAR2(50),
    APELLIDO_MATERNO VARCHAR2(50),
    ID_DIRECCION NUMBER,
    ID_SUCURSAL NUMBER,
    ID_CLIENTE NUMBER,
    CONSTRAINT PK_LTEB_BARBERO PRIMARY KEY (ID_BARBERO),
    CONSTRAINT FK_LTEB_BARBERO_DIRECCION FOREIGN KEY (ID_DIRECCION) REFERENCES LTEB_DIRECCION(ID_DIRECCION),
    CONSTRAINT FK_LTEB_BARBERO_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES LTEB_SUCURSAL(ID_SUCURSAL)
);

CREATE TABLE LTEB_HORA_DISPONIBLE_BARBERO(
    ID_BARBERO NUMBER,
    ID_HORA NUMBER,
    CONSTRAINT PK_LTEB_HORA_DISPONIBLE_BARBERO PRIMARY KEY (ID_BARBERO,ID_HORA),
    CONSTRAINT FK_LTEB_HORA_DISPONIBLE_BARBERO_BARBERO FOREIGN KEY (ID_BARBERO) REFERENCES LTEB_BARBERO(ID_BARBERO),
    CONSTRAINT FK_LTEB_HORA_DISPONIBLE_BARBERO_HORA FOREIGN KEY (ID_HORA) REFERENCES LTEB_HORA_DISPONIBLE(ID_HORA)
);

CREATE TABLE LTEB_BARBERO_ESPECIALIDAD(
    ID_BARBERO NUMBER,
    ID_ESPECIALIDAD NUMBER,
    CONSTRAINT PK_LTEB_BARBERO_ESPECIALIDAD PRIMARY KEY (ID_BARBERO,ID_ESPECIALIDAD),
    CONSTRAINT FK_LTEB_BARBERO_ESPECIALIDAD_BARBERO FOREIGN KEY (ID_BARBERO) REFERENCES LTEB_BARBERO(ID_BARBERO),
    CONSTRAINT FK_LTEB_BARBERO_ESPECIALIDAD_ESPECIALIDAD FOREIGN KEY (ID_ESPECIALIDAD) REFERENCES LTEB_ESPECIALIDAD(ID_ESPECIALIDAD)
);

CREATE TABLE LTEB_BARBERO_TURNO(
    ID_BARBERO NUMBER,
    ID_TURNO NUMBER,
    CONSTRAINT PK_LTEB_BARBERO_TURNO PRIMARY KEY (ID_BARBERO,ID_TURNO),
    CONSTRAINT FK_LTEB_BARBERO_TURNO_BARBERO FOREIGN KEY (ID_BARBERO) REFERENCES LTEB_BARBERO(ID_BARBERO),
    CONSTRAINT FK_LTEB_BARBERO_TURNO_TURNO FOREIGN KEY (ID_TURNO) REFERENCES LTEB_TURNO(ID_TURNO)
);

CREATE TABLE LTEB_CITA(
    ID_CITA NUMBER,
    ID_CLIENTE NUMBER,
    ID_SERVICIO NUMBER,
    ID_BARBERO NUMBER,
    FECHA DATE,
    HORA_INICIO VARCHAR2(50),
    ESTADO VARCHAR2(10),
    CONSTRAINT PK_LTEB_CITA PRIMARY KEY (ID_CITA),
    CONSTRAINT FK_LTEB_CITA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES LTEB_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_LTEB_CITA_SERVICIO FOREIGN KEY (ID_SERVICIO) REFERENCES LTEB_SERVICIO(ID_SERVICIO),
    CONSTRAINT FK_LTEB_CITA_BARBERO FOREIGN KEY (ID_BARBERO) REFERENCES LTEB_BARBERO(ID_BARBERO)
);

CREATE TABLE LTEB_EVALUACION(
    ID_EVALUACION NUMBER,
    ID_CITA NUMBER,
    CALIFICACION NUMBER,
    COMENTARIO VARCHAR2(200),
    CONSTRAINT PK_LTEB_EVALUACION PRIMARY KEY (ID_EVALUACION),
    CONSTRAINT FK_LTEB_EVALUACION_CITA FOREIGN KEY (ID_CITA) REFERENCES LTEB_CITA(ID_CITA)
);

CREATE TABLE LTEB_PAGO(
    ID_PAGO NUMBER,
    FECHA_PAGO DATE,
    MONTO NUMBER,
    METODO_PAGO VARCHAR2(70),
    ID_VENTA NUMBER,
    ID_CITA NUMBER,
    CONSTRAINT PK_LTEB_PAGO PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_LTEB_PAGO_VENTA FOREIGN KEY (ID_VENTA) REFERENCES LTEB_VENTA(ID_VENTA),
    CONSTRAINT FK_LTEB_PAGO_CITA FOREIGN KEY (ID_CITA) REFERENCES LTEB_CITA(ID_CITA)
);